# Generated by Django 4.2.3 on 2023-09-21 12:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_auto_20200508_1810'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=255)),
                ('message', models.CharField(max_length=500)),
                ('time', models.TimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
